In [79]:
import numpy as np

In [80]:
class Node(object):  # 16X16 
    def __init__(self, row_bag, col_bag, reg_bag, value = 0):
        self.value = value
        self.row_bag = row_bag
        self.col_bag = col_bag
        self.reg_bag = reg_bag
    
    def _is_valid(self, bo):
        condition1 = self.value in self.row_bag
        condition2 = self.value in self.col_bag
        condition3 = self.value in self.reg_bag  
        
        if condition1 or condition2 or condition3:
            return False
        return True
    

In [81]:
class Board(object):
    def __init__(self, bo):
        self.bo = bo
        self.len = len(bo)
        self.done = False
        self.all_possible = {1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16}
        
    @staticmethod    
    def _get_reg_num(row, col):  # (0,0) to (3,3)
        start_row = (row//4) 
        start_col = (col//4)
        return start_row, start_col        
    
    def _get_row(self, row):
        row_bag = set()
        for item in self.bo[row]:
            row_bag.add(item)
        return row_bag
    
    def _get_col(self, col):
        col_bag = set()
        for item in self.bo[:,col]:
            col_bag.add(item)
        return col_bag
    
    def _get_region(self, reg_x, reg_y):
        bag_of_num = set()        
        for i in range(reg_x * 4, reg_x * 4 + 4):
            for j in range(reg_y * 4, reg_y * 4 + 4):
                bag_of_num.add(self.bo[i][j])
        return bag_of_num
    
    def solve_board(self):
        next_pos = self.find_empty()
        if next_pos is None:
            return True
        else:
            row, col = next_pos
            reg_x, reg_y = self._get_reg_num(row, col)
            row_bag = self._get_row(row)
            col_bag = self._get_col(col)
            reg_bag = self._get_region(reg_x, reg_y)
            possible_bag = self.all_possible - (row_bag|col_bag|reg_bag)
#             print(possible_bag)
        for index, value in enumerate(possible_bag):
            next_node = Node(row_bag, col_bag, reg_bag, value)
            if next_node._is_valid(self.bo):
                self.bo[row][col] = value
#                 print("add value:", value)
                if self.solve_board():
                    return True
                else:
#                     print("remove:", self.bo[row][col])
                    self.bo[row][col] = 0
                    
        return False        

    
    def find_empty(self):
        for row in range(self.len):
            for col in range(len(self.bo[row])):
                if self.bo[row][col] == 0:
                    return row, col                
        return None
                
    def print_board(self):
        for i in range(len(self.bo)):
            if i % 4 == 0 and i != 0:
                print("- - - - - - - - - - - - - - - - - - - - -")

            for j in range(len(self.bo[0])):
                if j % 4 == 0 and j != 0:
                    print(" | ", end="")

                if j == 15:  # change line
                    print(self.bo[i][j])
                else:
                    print(str(self.bo[i][j]) + " ", end="")
                
   

In [82]:
s = (16,16)
zero_board = np.zeros(s, dtype=int)
zero_board[5][5] = 5
zero_board[8][8] = 8
zero_board[11][11] = 11

print(zero_board)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [83]:
%%time
bd1 = Board(zero_board)
bd1.solve_board()
# bd1.print_board()

CPU times: user 2.62 s, sys: 4 ms, total: 2.63 s
Wall time: 2.63 s


True

In [84]:
bd1.print_board()

1 2 3 4  | 5 6 7 8  | 9 10 11 12  | 16 13 14 15
5 6 7 8  | 1 2 3 4  | 16 13 14 15  | 9 10 11 12
9 10 11 12  | 16 13 14 15  | 1 2 3 4  | 8 5 6 7
16 13 14 15  | 9 10 11 12  | 5 8 6 7  | 1 2 3 4
- - - - - - - - - - - - - - - - - - - - -
2 1 4 3  | 6 7 8 9  | 10 5 16 13  | 11 12 15 14
6 7 8 9  | 2 5 1 3  | 11 12 15 14  | 10 16 4 13
10 5 16 11  | 12 14 15 13  | 2 1 4 8  | 3 9 7 6
12 14 15 13  | 10 16 4 11  | 3 9 7 6  | 2 8 1 5
- - - - - - - - - - - - - - - - - - - - -
3 4 1 2  | 7 9 5 16  | 8 15 12 10  | 6 14 13 11
7 8 5 16  | 3 11 2 1  | 6 14 13 9  | 4 15 12 10
11 9 10 6  | 13 15 12 14  | 4 16 1 5  | 7 3 8 2
13 15 12 14  | 8 4 10 6  | 7 3 2 11  | 5 1 16 9
- - - - - - - - - - - - - - - - - - - - -
8 11 9 1  | 4 12 13 2  | 14 6 10 16  | 15 7 5 3
4 16 13 10  | 14 8 9 7  | 15 11 5 3  | 12 6 2 1
14 3 6 7  | 15 1 16 5  | 12 4 9 2  | 13 11 10 8
15 12 2 5  | 11 3 6 10  | 13 7 8 1  | 14 4 9 16


In [62]:
a = {1,2,3,4}
b = {1}
c = {2,3}
d = {0,1,2}
result = a - (b|c|d)
print(result)
for i,value in enumerate(result):
    print(value)

{4}
4


In [5]:
a = {1,2}
b = {1,3}
c = a|b
print(c)

{1, 2, 3}


In [18]:
a = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}
for index, value in enumerate(a):
    print(value)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16


In [12]:
a = (1,2)
a[0]

1

In [16]:
a = 2
for i in range(a*3, a*5):
    print(i)

6
7
8
9


In [7]:
a = {1,2,3}
b = 2
print(b in a)

True


In [4]:
for i in range(0,3):
    print(i)

0
1
2


In [5]:
abs(0-3)

3

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

In [73]:
board = [
    [7,8,0,4,0,0,1,2,0],
    [6,0,0,0,7,5,0,0,9],
    [0,0,0,6,0,1,0,7,8],
    [0,0,7,0,4,0,2,6,0],
    [0,0,1,0,5,0,9,3,0],
    [9,0,4,0,6,0,0,0,5],
    [0,7,0,3,0,0,0,1,2],
    [1,2,0,0,0,7,4,0,0],
    [0,4,9,2,0,6,0,0,7]
]


def solve(bo):    
    next_pos = find_empty(bo)   
    if find_empty(bo) is None:
        return True   # use a boolen to stop the recursion
    else:    
        pos_x, pos_y = next_pos
    for num in range(1,17):
        if valid(bo, num, next_pos):
            bo[pos_x][pos_y] = num
            if solve(bo):
                return True
            else:    
                bo[pos_x][pos_y] = 0
    return False


def valid(bo, num, pos):  # pos: (i,j) row, col
    # check row
    for j in range(len(bo[pos[0]])):
        if num == bo[pos[0]][j] and j != pos[1]:
            return False
    # check col
    for i in range(len(bo[pos[1]])):
        if num == bo[i][pos[1]] and i != pos[0]:
            return False
    # check cube, which box //3
    box_x = pos[0] // 4
    box_y = pos[1] // 4
    index_x = 4 * box_x
    index_y = 4 * box_y
    for i in range(index_x, index_x+4):
        for j in range(index_y, index_y+4):
            if num == bo[i][j] and pos != (i,j):
                return False 
    return True


def print_board(bo):
    for i in range(len(bo)):
        if i % 4 == 0 and i != 0:
            print("- - - - - - - - - - - - - - - - - - - - -")

        for j in range(len(bo[0])):
            if j % 4 == 0 and j != 0:
                print(" | ", end="")

            if j == 15:  # change line
                print(bo[i][j])
            else:
                print(str(bo[i][j]) + " ", end="")


def find_empty(bo):
    for i in range(len(bo)):
        for j in range(len(bo[0])):
            if bo[i][j] == 0:
                return i, j  # row, col

    return None


In [77]:
s = (16,16)
zero_board = np.zeros(s, dtype=int)
zero_board[5][5] = 5
zero_board[8][8] = 8
zero_board[11][11] = 11
print(zero_board)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  8  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0 11  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]]


In [78]:
%%time
solve(zero_board)


CPU times: user 11 s, sys: 0 ns, total: 11 s
Wall time: 11 s


True

In [76]:
print_board(zero_board)

1 2 3 4  | 5 6 7 8  | 9 10 11 12  | 13 14 15 16
5 6 7 8  | 1 2 3 4  | 13 14 15 16  | 9 10 11 12
9 10 11 12  | 13 14 15 16  | 1 2 3 4  | 5 6 7 8
13 14 15 16  | 9 10 11 12  | 5 6 7 8  | 1 2 3 4
- - - - - - - - - - - - - - - - - - - - -
2 1 4 3  | 6 7 8 9  | 10 5 12 11  | 14 13 16 15
6 7 8 9  | 2 5 1 3  | 14 13 16 15  | 4 11 12 10
10 5 12 11  | 14 13 16 15  | 2 1 4 3  | 6 7 8 9
14 13 16 15  | 4 11 12 10  | 6 7 8 9  | 2 1 5 3
- - - - - - - - - - - - - - - - - - - - -
3 4 1 2  | 7 9 5 6  | 8 12 10 13  | 15 16 14 11
7 8 5 6  | 3 1 2 11  | 15 16 9 14  | 10 12 4 13
11 12 9 13  | 15 16 10 14  | 3 4 1 2  | 7 8 6 5
15 16 10 14  | 8 12 4 13  | 7 11 5 6  | 3 9 1 2
- - - - - - - - - - - - - - - - - - - - -
4 3 2 1  | 11 8 6 5  | 12 9 13 7  | 16 15 10 14
8 9 6 5  | 12 3 13 1  | 16 15 14 10  | 11 4 2 7
12 11 13 10  | 16 15 14 7  | 4 3 2 1  | 8 5 9 6
16 15 14 7  | 10 4 9 2  | 11 8 6 5  | 12 3 13 1


In [288]:
s = (16,16)
zero_board = np.zeros(s, dtype=int)
print(zero_board)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]


In [289]:
%%time
bd1 = Board(zero_board)
bd1.solve_board()
bd1.print_board()

1 2 3 4  | 5 6 7 8  | 9 10 11 12  | 13 14 15 16
5 6 7 8  | 1 2 3 4  | 13 14 15 16  | 9 10 11 12
9 10 11 12  | 13 14 15 16  | 1 2 3 4  | 5 6 7 8
13 14 15 16  | 9 10 11 12  | 5 6 7 8  | 1 2 3 4
- - - - - - - - - - - - - 
2 1 4 3  | 6 5 8 7  | 10 9 12 11  | 14 13 16 15
6 5 8 7  | 2 1 4 3  | 14 13 16 15  | 10 9 12 11
10 9 12 11  | 14 13 16 15  | 2 1 4 3  | 6 5 8 7
14 13 16 15  | 10 9 12 11  | 6 5 8 7  | 2 1 4 3
- - - - - - - - - - - - - 
3 4 1 2  | 7 8 5 6  | 11 12 9 10  | 15 16 13 14
7 8 5 6  | 3 4 1 2  | 15 16 13 14  | 11 12 9 10
11 12 9 10  | 15 16 13 14  | 3 4 1 2  | 7 8 5 6
15 16 13 14  | 11 12 9 10  | 7 8 5 6  | 3 4 1 2
- - - - - - - - - - - - - 
4 3 2 1  | 8 7 6 5  | 12 11 10 9  | 16 15 14 13
8 7 6 5  | 4 3 2 1  | 16 15 14 13  | 12 11 10 9
12 11 10 9  | 16 15 14 13  | 4 3 2 1  | 8 7 6 5
16 15 14 13  | 12 11 10 9  | 8 7 6 5  | 4 3 2 1
CPU times: user 99.7 ms, sys: 4.03 ms, total: 104 ms
Wall time: 95.8 ms
